lib/install/install.rb

The `lib/install/install.rb` script is missing `.tap` in the append to `config/initializers/assets.rb` file and so does actually set any of the passed assets/directories. The tests did not pick up on this, because the dummy app correctly uses .tap in it.
Thanks again for blazing the trail on ESM and Rails! Love that it's been extracted to a separate repo :)

.tap that path

---

test/reloader_test.rb

Looks like this maybe a linux thing. Everything passes fine on my mac but looks like the tests in Rails around the FileUpdateChecker also use `sleep 1` to ensure there's a new mtime.

Fix Reloader CI failure

---

lib/importmap/map.rb
test/importmap_test.rb

The `config/importmap.rb` that gets generated [invites you to map all your vendor assets](https://github.com/rails/importmap-rails/blob/main/lib/install/install.rb#L36-L38). It doesn’t actually work as advertised. The problem is, when you have a directory pinned without specifying `to:` or `under:`, the paths resolved for the files have a leading slash. `my_lib` becomes `/my_lib`. You then end up with a request to `app.test/my_lib.js`, which obviously doesn’t work. Sprockets won’t do anything with the path — doesn’t transform it, doesn’t complain — so we don’t even get [the warning](https://github.com/rails/importmap-rails/blob/main/lib/importmap/map.rb#L49-L50) you normally do when you ask for a path to a non-existent file.
This fixes all that.

Stop adding a leading slash to filenames

---

app/helpers/importmap/importmap_tags_helper.rb

Using the splat operator as a method argument without parentheses throw a warning `'*' interpreted as argument prefix`
https://buildkite.com/rails/rails/builds/80621#ba67a8c1-b5e6-42de-9b27-38e63e9356d3
Fixes #15

Fix warning message in importmap tags helper

---

Gemfile.lock
importmap-rails.gemspec
lib/importmap/packager.rb
test/packager_integration_test.rb
test/packager_test.rb

That's quite a lot of dependencies for a single HTTP POST.
Net::HTTP is a little clunkier to use, but it does the job fine.

Remove dependency on httparty

---

lib/importmap/map.rb

A minor tweak to `instance_eval` in the `draw` method, which allows the use of `__dir__` (and similar) in `importmap.rb`.
Useful when composing importmaps, for example from Rails Engines:
```ruby
initializer "importmap" do |app|
app.config.importmap.draw(Engine.root.join("config/importmap.rb"))
end
```
```ruby
pin_all_from File.expand_path("../app/assets/javascripts", __dir__)
```

allow to use `__dir__` in `importmap.rb` files

---

README.md

After discovering the Apollo Devtools Chrome extension was interrupting the loading of import-map, it seems prudent to add a disclaimer about this for future importmap-rails users.

Added notice re browser extensions blocking import maps

---

lib/importmap/commands.rb

Fixes #38
This command is supposed to print the importmap JSON, but it has been printing `null` since 75f312b21eebe31b5d9411ceac7c8cdb93e1ee5d because that commit delayed the construction of the `Importmap::Map` instance. It was previously constructed at class-evaluation-time (i.e. as soon as `importmap/engine.rb` was loaded), but now it's constructed in an initializer:
https://github.com/rails/importmap-rails/commit/75f312b21eebe31b5d9411ceac7c8cdb93e1ee5d#diff-5dac3d58ec92e0c2cba54981b8ff708a46dd3650b323dcfd9edccb25aac48ff1
In other words, loading `config/application.rb`, like we do here:
https://github.com/rails/importmap-rails/blob/7aa75e4f6fee00178167ec45b276d2f09fd2fe85/lib/install/bin/importmap#L3
used to be enough to use `Rails.application.config.importmap`, but it's no longer …

Fix broken `bin/importmap json` command

---

.github/workflows/ci.yml

This is a follow-up to #39 which fixed a bug in the `bin/importmap json` command: we're adding a minor check to CI to verify that the command prints a JSON object containing `imports`.

Add a step to check the `bin/importmap json` command on CI

---

lib/tasks/importmap_tasks.rake

The `importmap:pins` rake task was added in f42f53e91bae9324a1a6f85e0bc03914ca372b03 before the `bin/importmap` CLI existed. Its function is identical to the `bin/importmap json` command, though, so I'm proposing we remove the rake task in an effort to consolidate around just the `bin/importmap` CLI (which also hosts the `pin` and `unpin` commands).

Remove `importmap:pins` rake task in favor of `bin/importmap json` CLI

---

README.md
lib/install/config/importmap.rb

Given that a major benefit of using the default importmap-rails approach is that you don't need nodejs at all, I think we should avoid using the term "node modules" and instead use "npm packages". This should hopefully avoid confusion/misunderstanding where folks mistakenly think they still need to install node: The CDNs allow them to still leverage the npm ecosystem even if their system doesn't have nodejs nor any local `node_modules` directories.

Avoid mentioning "node" in importmap.rb template and README

---

README.md

The importmap object is not in the config anymore and the order of loading matters.

Update guide for engines

---

README.md

Adds the docs clarifications from https://github.com/rails/importmap-rails/issues/46.

docs: note Firefox asm.js warning

---

lib/importmap/engine.rb
lib/importmap/map.rb

As noted in https://github.com/rails/importmap-rails/issues/42, the gem had a direct reference to a constant from sprockets-rails here:
https://github.com/rails/importmap-rails/blob/8d66a09efa9e5d43f7f2e5150b0ccb45c08a8220/lib/importmap/map.rb#L94
This is problematic because consumers may be using a different asset pipeline than sprockets-rails. In that case, when `Importmap::Map#resolve_asset_paths` invokes the application's `asset_path` helper method, it may need to rescue different exceptions than `Sprockets::Rails::Helper::AssetNotFound`.
To support that, we've added a `rescuable_asset_errors` property to the importmap configuration options. We automatically add `Sprockets::Rails::Helper::AssetNotFound` to the list if `Sprockets::Rails` is defined, which should allow the gem to work …

Decouple from sprockets-rails

---

lib/importmap/commands.rb

`options[:provider]` was renamed to `options[:from]`

Fix reference to renamed pin/unpin option

---

README.md

with importmaps being the default in Rails 7, I think it's important for those not familiar with importmaps to have a brief description of what importmaps are and how they work without having to visit external resources.

docs: explain "why" importmaps + how they work.

---

README.md
lib/importmap/engine.rb
lib/importmap/reloader.rb

These changes allow using reloader and cache sweepers in Rails engines.

Make importmap paths configurable

---

README.md

The following is a very neat DSL, but I'm pretty certain it isn't valid ruby.  ;)
````
pin "react" to "https://ga.jspm.io/npm:react@17.0.2/index.js"
````

Fix README ruby syntax error

---

gemfiles/rails_7_propshaft.gemfile.lock
gemfiles/rails_7_sprockets.gemfile.lock

Without this, running `bundle install` with `BUNDLE_GEMFILE` set to one of these gemfiles will result in an error like:
```
You are trying to install in deployment mode after changing your
Gemfile. Run `bundle install` elsewhere and add the updated
gemfiles/rails_7_propshaft.gemfile.lock to version control.
```
as seen in the CI run for the commit that bumped the version:
https://github.com/rails/importmap-rails/runs/4297724678?check_suite_focus=true#step:3:30

Update additional lockfiles after bumping importmap-rails version

---

lib/importmap/engine.rb

While working on #61, I noticed a minor style inconsistency between the `"importmap.assets"` initializer and the rest of the initializers declared in `lib/importmap/engine.rb`: That one directly references `Rails.application` while the others use the `app` block variable (which makes the code a bit more concise). So this PR is nothing groundbreaking; it just makes them consistent.

Use consistent style in "importmap.assets" initializer

---

bin/release
gemfiles/rails_7_propshaft.gemfile.lock
gemfiles/rails_7_sprockets.gemfile.lock

Related: #75
CI broke again after we bumped the version to 0.9.1:
https://github.com/rails/importmap-rails/runs/4309148366?check_suite_focus=true#step:3:30
This PR updates the additional gemfiles again to reference the new version, which fixes CI (f0f3c1177504e8acc652a8321171e8b3fd05b8e7). Additionally, after discovering the `bin/release` script, I've enhanced it to handle this automatically going forward (77a5b5efa60b6aadd5ea8ca4c674db16dea951af).

Fix extra lockfiles again & update release script to handle that automatically

---

gemfiles/rails_7_propshaft.gemfile.lock
gemfiles/rails_7_sprockets.gemfile.lock

This can be done through the appraisal gem via
`bundle exec appraisal install`
or just through bundler via
`for gemfile in $(ls gemfiles/*.gemfile); do BUNDLE_GEMFILE="$gemfile" bundle; done`

Update additional lockfiles to fix CI failures in #84

---

Gemfile.lock
gemfiles/rails_7_propshaft.gemfile.lock
gemfiles/rails_7_sprockets.gemfile.lock
importmap-rails.gemspec

Cut down on the necessary dependencies

---

lib/importmap/map.rb

If you're using a custom asset host resolver, you may need to use separate caches for the preloaded module paths and json returns. Otherwise the first resolved asset host will be used to generate these values, which as then cached for all subsequent requests.
We use this in HEY as a consequence of the following asset host resolver:
```ruby
config.action_controller.asset_host = Proc.new do |source, request|
unless request&.user_agent.to_s.match?(/HEY iOS/) && source =~ /\.(css|js)$/
"https://production.haystack-assets.com"
end
end
```
That allows us to call `javascript_inline_importmap_tag` like so:
```ruby
javascript_inline_importmap_tag(Rails.application.importmap.to_json(
resolver: self, cache_key: "#{platform.ios_app? ? "ios_app" : "all"}_json"
))
```

Allow for custom cache keys for Importmap::Map#preloaded_module_paths and Importmap::Map#to_json

---

lib/importmap/map.rb
test/fixtures/files/invalid_import_map.rb
test/importmap_test.rb

This PR adds a test to cover an invalid importmap file and makes use of a custom error class for easier error tracking.
While I was in there I noticed we're rescuing `Exception`s rather than `StandardError`s when parsing importmap files. That's interesting to me as it's usually something I avoid doing—Exceptions are raised by events like a system interrupt, which I imagine we wouldn't want to swallow. I'm happy to remove that commit if it's required though 😄

Test invalid importmap file

---

lib/importmap/map.rb

Closes rails/rails#44403
If a route is defined that generates the helper `asset_path`, the `view_context` passed to `importmap.to_json` will use the resource route instead of the asset pipeline route. By default, this is aliased to `path_to_asset`, so updating this method to use that instead resolves the issue.

Prevent `asset_path` clashing with route definition in a rails app

---

test/packager_test.rb

Adds a test to cover `ImportMap::Packager#vendored_pin_for` and removes some unused code.

Add packager tests

---

lib/importmap/commands.rb
lib/importmap/npm.rb
test/fixtures/files/outdated_import_map.rb
test/fixtures/files/vulnerable_import_map.rb
test/npm_integration_test.rb
test/npm_test.rb

This adds two new commands to Importmap: `./bin/importmap audit` and `./bin/importmap outdated`.
Both commands use npm's endpoints to fetch the related data.
While `audit` has an endpoint where they accept multiple packages, I couldn't find any to retrieve the versions of multiple packages in order to decrease the requests for the `outdated` check; and thus it's doing one request for each package.
I initially used a much simpler regex to extract the name and version (`/^pin "([^"]*)".*@(\d+\.\d+\.\d+(?:[^\/\s]+)?).*$/`), but then I discovered that some packages are loaded from inside other packages, and thus I couldn't rely on the name provided to the `pin` method. For a better maintainability I've kept the two regex separate: 1 for remote dependencies, and 1 for local dependencies. The …

Add outdated and audit commands

---

README.md
lib/importmap/npm.rb
test/npm_test.rb

I've just noticed that #109 isn't working under 2.7 (my bad on not trying that version locally and thinking that it'd run on CI before getting merged :grimacing: :man_facepalming:).
The reason is that Ruby 3.0 added the ability to set headers on the `Net::HTTP.get` call, while 2.7 doesn't have that, and so it breaks.
This fixes that by changing the Get request.
I've tried and the `Content-Type` header is not required by the NPM server (so a simple `Net::HTTP.get(uri)` would work), but I prefer sending it just to be future-proof in case they'll require it.
I've also added a couple of lines to the Readme to mention the two new commands.
It might be worth releasing a v1.1.1 with this fix. Sorry for the trouble :sweat_smile: 
/cc @dhh

Fix net http request on ruby 2.7

---

test/reloader_test.rb

This `sleep 1` was added in 2df91f6 to address CI failures, however this
has not appeared to fix the issues.
When investigating how the FileUpdateChecker tests worked in Rails, I
realized that the sleep is actually on the other side of the touch. Its
purpose is to ensure that there is separation between the create and
update times of the files (so that the reloader can identify the
change), so it should go before the touch.

Fix reloader test flakiness

---

app/helpers/importmap/importmap_tags_helper.rb
test/importmap_tags_helper_test.rb

Previously this would error because there is no request object in the
console for `content_security_policy_nonce` to be called on.
~This is based on #138 which should be merged first~ ✔️ 
Fixes rails/rails#44809

Fix using javascript_importmap_tag in console

---

app/helpers/importmap/importmap_tags_helper.rb

Addresses https://github.com/rails/importmap-rails/pull/139#pullrequestreview-1039675905
Resolves #142 (@agrieser can you please confirm?)
It seems that #139 accidentally swapped `content_security_policy_nonce` with `content_security_policy`, so we're switching them back to call `content_security_policy_nonce`.
Ideally we should backfill test coverage that exercises this properly so that CI would catch this type of bug. I don't currently have the bandwidth to do so, but hopefully we can still accept this fix and someone can add that as a follow-up.

Fix nonce attributes that were accidentally broken in PR #139

---

app/helpers/importmap/importmap_tags_helper.rb
test/importmap_tags_helper_test.rb

Regression tests for 357d7ba
The FakeRequest object is modeled after the one used for similar tests
for the Rails asset tags
https://github.com/rails/rails/blob/9994d38bc6c1a8662e510d26c0e9ca8c24ab1189/actionview/test/template/asset_tag_helper_test.rb#L27
cc @rmacklin Thanks for fixing this, sorry about that

Add more tests for helpers

---

lib/importmap/packager.rb
test/packager_single_quotes_test.rb

The default settings in Rubocop will change the double quotes in `config/importmap.rb` to single quotes.  This breaks the `bin/importmap pin` and `bin/importmap unpin` commands.
This simple patch will enable both commands to work with single quotes.

Allow single quotes in config/importmaps.rb

---

.github/workflows/ci.yml
Gemfile.lock
gemfiles/rails_7_propshaft.gemfile.lock
gemfiles/rails_7_sprockets.gemfile.lock

To get this to run green I had to upgrade Nokogiri in the lockfile.
Also added `fail-fast: false` to the CI configuration to make analyzing issues easier.
Runs green on my fork.

Adds Ruby 3.2 to the CI matrix. Also updates checkout action version.

---

lib/importmap/commands.rb
lib/importmap/npm.rb

While setting up my app, I've found a few times where I want to know what packages I have in my importmap, as well as their pinned version. I could use a regex to get that myself, but this feels like something that should really be built into importmap-rails.

Add a packages command to get package info

---

lib/importmap/engine.rb
lib/importmap/map.rb

Currently importmap-rails adds some file watchers even when `enable_reloading` is false. This PR fixes that. This way, the reloader will not run in a test environment where reloading is off by default.

Respect `config.enable_reloading`

---

app/helpers/importmap/importmap_tags_helper.rb
lib/importmap/packager.rb
test/importmap_tags_helper_test.rb

This is a great feature whenever you have separate areas of the application with completely different sets of dependencies.
The most common example of that is admin areas, both on the main Rails application or coming from engines.
SpinaCMS for example had to add a custom helper https://github.com/SpinaCMS/Spina/blob/400821ddd27aad76c0ff29ac603fb934b5d7e648/app/helpers/spina/spina_helper.rb

Add support for passing a custom importmap to the tag helper

---

lib/importmap/npm.rb
test/fixtures/files/single_quote_outdated_import_map.rb
test/fixtures/files/single_quote_outdated_import_map_without_cdn.rb
test/npm_test.rb

Related issue: https://github.com/rails/importmap-rails/issues/156
Wrapping strings with single-quotes in the `importmap.rb` file is not picked up by commands `audit` and `outdated`.
The `audit` and `outdated` commands should pick up pins where either double or single quotes are used.
The problematic lines are the following:
* https://github.com/rails/importmap-rails/blob/9eec49a9ea3feaab224871437cf1bc2479801796/lib/importmap/npm.rb#L51
* https://github.com/rails/importmap-rails/blob/9eec49a9ea3feaab224871437cf1bc2479801796/lib/importmap/npm.rb#L52
The regex are designed to only scan for double-quotes. The proposed change adds in detection for double-quotes and single-quotes.
The implementation proposed is a bit naive in that strings wrapped with one double-quote and one single-quote will …

Add single quote support in `importmap.rb`

---

lib/importmap/map.rb
test/dummy/app/assets/config/manifest.js
test/dummy/config/initializers/assets.rb
test/importmap_test.rb

While using ViewComponents I ran into an issue with sidecar loaded js files not being mapped correctly when using importmap-rails and propshaft. The issue has been raised in [Propshaft Issue #87](https://github.com/rails/propshaft/issues/87) and [ViewComponents Issue #1064](https://github.com/ViewComponent/view_component/issues/1064) neither of which provided solutions I wanted to use.
Digging into it I found that using the following config nearly produced the desired output:
```ruby
Rails.application.config.assets.paths << "app/components"
pin_all_from "app/components", under: "controllers", to: ""
{
"imports": {
"controllers/button/component_controller": "/button/component_controller.js"
}
}
```
I assume Propshaft interprets the path as absolute and fails to digest it.
This fix just …

Remove prepended forward slash when mapping.path is empty

---

test/installer_test.rb

This commit adds test coverage for the installer Rake task and application template.  The installer is run against a freshly generated Rails app using the version of Rails that is currently loaded.  Thus the installer can be tested with different versions of Rails in CI.

Test installer

---

lib/tasks/importmap_tasks.rake

This prevents an error when the template path contains characters that should be escaped.  For example, if the `importmap-rails` gem is installed in a directory that has whitespace characters in its path. Avoiding a subshell is also more performant.

Use non-subshell `system` variant in installer

---

README.md
lib/importmap/commands.rb

The idea of depending on a CDN to serve assets doesn't actually make sense in a HTTP/2 world. You pay a price per domain you connect to, so you should just serve all your assets, including npm dependencies, off your own domain.
We originally went with CDNs as default out of a fear that people would be squeamish about vendoring compiled libraries together with their source code. But that's just silly. Static linking has a long, proud history, and this is the equivalent of that.

Pinning should just always download

---

README.md
lib/importmap/map.rb
test/dummy/config/importmap.rb
test/importmap_test.rb

An app has to be very large to benefit from partial/on-demand loading. And that's the only time where you wouldn't want to preload your dependencies, because the cost of water falling would be less than the cost of loading it all. For most applications, you'd rather have zero waterfall by default, and load all your JavaScript up front. So that should be the default.

Preload all by default

---

README.md

Reading through the docs again after #218 I noticed the wording seemed to be off in the "Preloading pinned modules" docs section so this is my suggested fix.

Fix wording in preloading pinned modules docs

---

lib/importmap/commands.rb

Proposal to make the command table markdown compatible, so it's easier to copy the table and paste directly in any markdown (normally the PR description) and display it with the correct styles.
```shell
➜  dummy git:(main) ✗ bin/importmap outdated
+-------------------+---------+--------+
| Package           | Current | Latest |
+-------------------+---------+--------+
| @rails/request.js | 0.0.6   | 0.0.9  |
+-------------------+---------+--------+
1 outdated package found
➜  dummy git:(main) ✗ bin/importmap outdated
| Package           | Current | Latest |
|-------------------|---------|--------|
| @rails/request.js | 0.0.6   | 0.0.9  |
1 outdated package found
```
Also displaying the table here:
Old:
+-------------------+---------+--------+
| Package           | Current | Latest | …

Update Impoortmaps::Command#puts_table to be markdown compatible

---

lib/importmap/packager.rb
test/packager_integration_test.rb

Now that the packages are downloaded by default, apart from the output of the `pin` command we lose the track of the version and from where the package was downloaded. To track the version the solution was use a comment in bin/importmap next to the package version but nothing for the package origin so the proposal is add a comment in the first line of the downloaded package displaying the package name, version and from where it was downloaded.

Add package information in vendored package file

---

lib/importmap/packager.rb

Coming from https://github.com/basecamp/local_time/issues/113#issuecomment-1891982065
I realized the HTTP request in `Importmap::Packager#import` was returning HTTP401:
```
Code:
401
Body:
{"error":"Error: No provider named \"jspm\" has been defined."}
```
This matches the behavior of a test that's currently failing:
```sh
❯ bin/test test/packager_integration_test.rb
Error:
Importmap::PackagerIntegrationTest#test_successful_import_against_live_service:
NoMethodError: undefined method `[]' for nil:NilClass
/Users/jose/my_repos/importmap-rails/test/packager_integration_test.rb:8:in `block in <class:PackagerIntegrationTest>'
bin/test /Users/jose/my_repos/importmap-rails/test/packager_integration_test.rb:7
```
This happens because `Importmap::Packager#import` returns `nil` when the HTTP …

Update default provider to use `jspm.io` instead of `jspm`

---

README.md

Since the bundled shim was dropped in #216 and there still exist legacy browsers that are still maintained but that do not support import maps such as Safari on iOS 15, how to support the legacy browsers should be mentioned in the README.

Add how to support legacy browsers to README

---

lib/importmap/map.rb
test/dummy/app/javascript/controllers/special_index.js
test/dummy/app/javascript/helpers/requests/special_index.js
test/importmap_test.rb

* Closes https://github.com/rails/importmap-rails/issues/215
This updates the regex used to identify index files to ensure that modules like `foo/special_index` don't get mapped to `foo`.
The cause of the problem was that the previous regex matched 1 or 0 `/` characters, which meant anything followed by `index` and the end of the string, would qualify. We now ensure that we match either the start of the string or `/`

Updated module_name regexp to not match incorrect indexes

---

lib/tasks/importmap_tasks.rake
test/installer_test.rb

* Closes https://github.com/rails/importmap-rails/issues/204
This commit moves from using the `system` function which invokes the Rakefile twice and moves to use `Rake::Task[].invoke` which similarly calls `app:template` but doesn't reload the Rakefile

Invoke app:template via Rake::Task[].invoke to avoid reloading rakefile

---

lib/importmap/npm.rb
test/npm_test.rb

Closes https://github.com/rails/importmap-rails/issues/245
It is expected NPM to return a Hash for the response.
https://github.com/rails/importmap-rails/blob/ddf9be434e0aca1103eabafe6d34b0e8a5064057/lib/importmap/npm.rb#L89
But for whatever reason the response can now also return a String, which is not accounted for in `npm.rb`.
See the referenced issue for further context.
The `importmap outdated` command should handle the problem more gracefully. In this case, a reasonable expectation is to surface the String response.
How to handle is up for discussion.
Just to get the fix process started the propose change is to surface the String in the response as `latest_version` since it isn't clear what the contents of the String could be.
Using the fork with change on our production app which …

Handle String response for "find latest version"

---

README.md
app/helpers/importmap/importmap_tags_helper.rb
lib/importmap/map.rb
test/importmap_test.rb

As discussed in https://github.com/rails/importmap-rails/issues/240#issuecomment-1998340405, this PR allows preload to accept 1+ strings representing entry_points instead of just a boolean for the value of a mapping's preload. That way you can forgo creating multiple importmaps and instead use an application-wide importmap and modify what is preloaded based on where you are.

Allows preload to be determined by provided entry_point

---

lib/importmap/commands.rb
test/commands_test.rb

This aims to fix #228
Also adds tests for the `./bin/importmap update` command.
I tried to investigate when this stopped working but could not pinpoint it. Tried various older Ruby versions and older Importmap versions but did not find anything.

Fix ./bin/importmap update

---

app/helpers/importmap/importmap_tags_helper.rb

Determining preload by provided entry_point (See #253) can result in a cached version of the preload tags to be rendered, based on another entry_point. To prevent that, use the provided entry_point as the cache key.

Use entry_point as cache_key when generating preload tags

---

lib/importmap/commands.rb
test/commands_test.rb

I was trying to keep #237 working on RubyGems.org and ran into the problem of the new comments being added to the file. This command redownloads files without changing which version is used.
This is a substitute for manually running `bin/importmap pin pkg@1.2.3` for each package.

Adds `bin/importmap pristine` which redownloads pinned packages

---

lib/importmap/commands.rb

In #271 I made the mistake of leaving `*packages` in the args. They are ignored, so remove them.
cc: @dhh

Correct pristine command description and args

---

README.md

This PR updates the JavaScript CDN section of the README, and adds examples for using `--from` with unpkg and jsdelivr.

Update JavaScript CDN section of README

---

lib/importmap/commands.rb
lib/importmap/packager.rb
test/packager_test.rb

In the [HotDocs installer](https://github.com/3v0k4/hotdocs/blob/49c2f322eab16e05d6b7b5fea150d4627b55a1e9/lib/install/install.rb#L26), I'd like to specify the preload when `pin`ning a package. Otherwise, I'd need to manually fiddle with the `config/importmap.rb` file.
This PR takes care of two things:
- Fix the tests in the first commit
- Add the `--preload` option to `pin` (e.g., `bin/importmap pin --preload=false lunr`, `bin/importmap pin --preload=application --preload=alternate lunr`) in the second commit; see the test for the specifics on the behavior
Thanks for your work on this gem!

Add `--preload` option to pin command

---

lib/importmap/npm.rb
test/npm_test.rb

And add a more descriptive error message.
Fixes #300

Catch failure HTTP responses on calls to the npm registry 

---

.github/workflows/ci.yml
Appraisals
Gemfile
Gemfile.lock
README.md
app/helpers/importmap/importmap_tags_helper.rb
gemfiles/rails_7.0_propshaft.gemfile
gemfiles/rails_7.1_propshaft.gemfile
gemfiles/rails_7.2_propshaft.gemfile
gemfiles/rails_8.0_propshaft.gemfile
gemfiles/rails_main_propshaft.gemfile
lib/importmap/commands.rb
lib/importmap/map.rb
lib/importmap/packager.rb
test/commands_test.rb
test/dummy/bin/importmap
test/dummy/config/importmap.rb
test/dummy/config/initializers/assets.rb
test/importmap_tags_helper_test.rb
test/importmap_test.rb
test/packager_integration_test.rb
test/packager_test.rb
test/reloader_test.rb

This pull request introduces Subresource Integrity (SRI) support to the importmap-rails gem, enhancing security by ensuring that JavaScript files loaded from CDNs have not been tampered with.
When you pin a package, integrity hashes are automatically included:
```bash
./bin/importmap pin lodash
Pinning "lodash" to vendor/javascript/lodash.js via download from https://ga.jspm.io/npm:lodash@4.17.21/lodash.js
Using integrity: sha384-PkIkha4kVPRlGtFantHjuv+Y9mRefUHpLFQbgOYUjzy247kvi16kLR7wWnsAmqZF
```
This generates a pin in your `config/importmap.rb` with the integrity hash:
```ruby
pin "lodash", integrity: "sha384-PkIkha4kVPRlGtFantHjuv+Y9mRefUHpLFQbgOYUjzy247kvi16kLR7wWnsAmqZF" # @4.17.21
```
If you need to disable integrity checking (not recommended for security reasons), you can use the …

Implement SRI support in importmap-rails
